name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Docker Hub credentials for the build job
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Project (skip tests)
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: Build Docker image
        run: docker build -t azan06/buildazan-rb:0.1 .

      - name: Push image to Docker Hub
        run: docker push azan06/buildazan-rb:0.1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Your runtime secrets made available to the deploy steps
    env:
      MONGO_DB_URI:      ${{ secrets.MONGO_DB_URI }}
      MONGO_DB_NAME:     ${{ secrets.MONGO_DB_NAME }}
      BREVO_API_KEY:     ${{ secrets.BREVO_API_KEY }}
      BREVO_SENDER_EMAIL: ${{ secrets.BREVO_SENDER_EMAIL }}

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          # give enough time for pulling/running the container
          command_timeout: 3m
          script: |
            # Pull the latest image
            sudo docker pull azan06/buildazan-rb:0.1

            # Remove old container (if any)
            sudo docker rm -f buildazan-rb-container || true

            # Run the container, injecting env vars
            sudo docker run -d \
              -p 8080:8080 \
              --name buildazan-rb-container \
              -e MONGO_DB_URI="$MONGO_DB_URI" \
              -e MONGO_DB_NAME="$MONGO_DB_NAME" \
              -e BREVO_API_KEY="$BREVO_API_KEY" \
              -e BREVO_SENDER_EMAIL="$BREVO_SENDER_EMAIL" \
              azan06/buildazan-rb:0.1

            echo "✅ Deployed at $(date)"
